SELECT CASE 
    WHEN STUDENTS.MARKS < 70 THEN 'NULL'
    ELSE STUDENTS.NAME
    END, GRADES.GRADE, STUDENTS.MARKS
FROM STUDENTS
LEFT JOIN GRADES ON STUDENTS.MARKS >= GRADES.MIN_MARK AND 
    STUDENTS.MARKS <= GRADES.MAX_MARK
ORDER BY GRADES.GRADE DESC, STUDENTS.NAME ASC;
