SELECT CAST(LAT_N AS DECIMAL (7,4))
FROM
    (SELECT LAT_N, ROW_NUMBER() OVER (ORDER BY LAT_N) as ROWN
     FROM STATION 
     ) AS X
WHERE ROWN = ( SELECT ROUND((COUNT(LAT_N)+1)/2,0) 
                FROM STATION
               );
